name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv
